language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw

script: "./mvnw clean package -DskipTests"

notifications:
  email:
    recipients:
      - open7894.v2@gmail.com