language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2'

before_install:
  - chmod +x mvnw
  - zip -r academy-aws-webservice *
  - mkdir -p deploy
  - mv academy-aws-webservice.zip deploy/academy-aws-webservice.zip

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp target/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/academy-aws-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myungjin-mall-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myungjin-mall-build
    key: academy-aws-webservice.zip
    bundle-type: zip
    application: academy-aws-webservice
    deployment-group: academy-aws-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

script: "./mvnw clean package -DskipTests"

notifications:
  email:
    recipients:
      - open7894.v2@gmail.com