server:
  port: 7060
spring:
  application:
    name: academy_demo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:academy;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    schema: classpath*:/db/h2/schema.sql
    data: classpath*:/db/h2/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  profiles:
    include: mail, cloud
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE