spring:
  application:
    name: academy_demo
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:academy;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true



server:
  port: 7090