server:
  port: 7090
spring:
  application:
    name: academy_demo
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  profiles:
    include: mail, cloud, real-db
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE