spring:
  application:
    name: academy_demo
  jpa:
    open-in-view: false
    show-sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  profiles:
    include: mail, cloud, real-db
server:
  port: 7090
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE