spring:
  application:
    name: academy_demo
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  profiles:
    include: mail, cloud, real-db
  datasource:
    schema: classpath*:/db/maria/schema.sql
    data: classpath*:/db/maria/data.sql
    initialization-mode: always
server:
  port: 7091
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE